from os.path import join
from bgspy.slim import SlimRuns

DATADIR = 'runs'

if not len(config):
    raise ValueError("config file not specified on command line, use --configfile config.json")

run = SlimRuns(config)

# generate all the targets for this YAML file.
all_sims = run.generate_targets()

## useful for debugging:
#print("all targets:")
#print(all_sims) 
#print("template:")
#print(run.output_template()) 
#print("slim call:")
#print(run.slim_cmd())

rule slim:
    input: run.script, **run.input
    output: **run.output_template()
    resources:
      time_min=10,
      mem_mb=10000
    shell: run.slim_cmd()

rule process_sims:
    input: sims=all_sims, dir=run.basedir
    output: "region_results.pkl"
    resources:
      time_min=120,
      mem_mb=70000,
      threads=40
    shell:
      """
      python ../../tools/process_region_sims.py {input.dir} {output}
      """

rule all:
    input: all_sims + ["region_results.pkl"]


