[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bgspy"
version = "0.01"
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "numpy",
    "scipy"
    ]
