from os.path import join
import json
import numpy as np
from bgspy.models import BGSModel 
from bgspy.genome import Genome

NCORES = 70
NCORES_BP = 40

# ===== For Simulations =====
# 
# Note: for next sim run, just use grid-string params, perhaps 
# non phastcons track.
#
CONFIG = '../../../slim_sims/chrombgs/chrombgs_chr10_thresh0.json'

chr10_sim_config = json.load(open(CONFIG))
print(chr10_sim_config)

# note: only the file stem is in the value, rest denotes chrom
cons_track = chr10_sim_config['cons_track'] + '_chr10.bed'
Ns = chr10_sim_config['params']['N']['grid']
assert(len(Ns) == 1)
sims_N = Ns[0]
# for w/t arguments to CL
t = ','.join(map(str, chr10_sim_config['params']['sh']['grid']))
w = ','.join(map(str, chr10_sim_config['params']['mu']['grid']))

rule bmap_chr10:
  input: annot=join("../../annotation/",  cons_track),
         seqlens_file="../../annotation/hg38_seqlens.tsv", 
         recmap="../../annotation/HapMapII_GRCh37_liftedOverTo_Hg38/genetic_map_Hg38_chr10.txt"
  output: pkl_b_file="bmap_hg38_sims_{step}step_chr10.pkl"
  params: ncores=NCORES, ncores_bp=NCORES_BP, popsize=sims_N, t=t, w=w
  shell:
    """
    python ../../../bgspy/command_line.py calcb \
      --recmap {input.recmap} --annot {input.annot} \
      --seqlens {input.seqlens_file} \
      --t {params.t} \
      --w {params.w} \
      --output {output} --popsize {params.popsize} --chrom chr10 \
      --ncores {params.ncores} --ncores-Bp {params.ncores_bp} \
      --step {wildcards.step}
    """

# ===== For Empirical Work =====

rule bmap_hg38:
  input: annot="../../annotation/merged_utrs_cds_introns_phastcons.bed.gz", 
         seqlens_file="../../annotation/hg38_seqlens.tsv", 
         recmap="../../annotation/hapmap_genetic_map.txt"
  output: pkl_b_file="bmap_hg38_{grid_str}grid_{step}step_10kN_mergedfeatures.pkl"
  params: ncores=NCORES, ncores_bp=NCORES_BP, popsize=10000
  shell:
    """
    python ../../../bgspy/command_line.py calcb \
      --recmap {input.recmap} --annot {input.annot} \
      --seqlens {input.seqlens_file} --g '{wildcards.grid_str}' \
      --output {output} --popsize {params.popsize} \
      --ncores {params.ncores} --ncores-Bp {params.ncores_bp} \
      --step {wildcards.step}
    """

rule bmap_hg38_genomiconly:
  input: annot="../../annotation/merged_utrs_cds_introns.bed.gz", 
         seqlens_file="../../annotation/hg38_seqlens.tsv", 
         recmap="../../annotation/hapmap_genetic_map.txt"
  output: pkl_b_file="bmap_hg38_{grid_str}grid_{step}step_10kN_genomiconly.pkl"
  params: ncores=NCORES, ncores_bp=NCORES_BP, popsize=10000
  shell:
    """
    python ../../../bgspy/command_line.py calcb \
      --recmap {input.recmap} --annot {input.annot} \
      --seqlens {input.seqlens_file} --g '{wildcards.grid_str}' \
      --output {output} --popsize {params.popsize} \
      --ncores {params.ncores} --ncores-Bp {params.ncores_bp} \
      --step {wildcards.step}
    """



## Target B maps for various purposes

maps = [
        "bmap_hg38_7x5grid_10000step_chr10.pkl",
        "bmap_hg38_6x7grid_10000step_chr10.pkl",
        #"bmap_hg38_20x21grid_10000step_chr10.pkl",
        "bmap_hg38_6x5grid_10000step_10kN_mergedfeatures.pkl",
         "bmap_hg38_6x5grid_10000step_10kN_genomiconly.pkl",
        # for the simulations (uses phastcons currently)
         "bmap_hg38_sims_10000step_chr10.pkl"
        ]

rule all:
  input: maps
