

rule counts_from_gvcf:
  input: "dragen_1kg_genotypes/ceu-chb-yri_{chrom}_genotyped_sorted.gvcf.gz"
  output: "hg1k_counts/{chrom}_counts.npy"
  shell:
    """
    python ../../tools/gvcf2counts.py --sample-file yri_samples.tsv --outdir hg1k_counts {input}
    """

chroms = list(range(1, 23)) + ['X']
counts = [f"hg1k_counts/chr{c}_counts.npy" for c in chroms]

rule all:
  input: counts
