if not len(config):
    raise ValueError("config file not specified on command line, use --configfile config.json")

# config file should have filename pattern mprime_bgs_{name}.json, 
# as it's loaded elsewhere here
name = config['name']
model = config['model']

# network architectures to try
archs = [dict(n128=0, n64=0, n32=0, n8=1),
         dict(n128=0, n64=0, n32=0, n8=2),
         dict(n128=0, n64=0, n32=0, n8=4),
         dict(n128=0, n64=0, n32=0, n8=8),
         dict(n128=0, n64=0, n32=1, n8=0),
         dict(n128=0, n64=0, n32=2, n8=0),
         dict(n128=0, n64=0, n32=4, n8=0),
         ]

archs = [dict(n128=0, n64=0, n32=2, n8=0)]



nsamples = [1000, 5_000, 10_000, 50_000, 100_000, 500_000, 1_000_000]

#activations = ['elu', 'relu', 'tanh']
activations = ['elu']

sim_file = f"../data/msprime_sims/msprime_bgs_{name}_{{nsamples}}nsamps.npz", 

# the learned func, pickled
data_file = f"../data/msprime_sims/msprime_bgs_{name}_{{nsamples}}.pkl"

MODEL_FILE = f"../data/msprime_sims/fits/{name}/msprime_bgs_{name}_{{nsamples}}nsamps_{{n128}}n128_{{n64}}n64_{{n32}}n32_{{n8}}n8_{{activ}}activ_{{rep}}rep.pkl"
KERAS_FILE = f"../data/msprime_sims/fits/{name}/msprime_bgs_{name}_{{nsamples}}nsamps_{{n128}}n128_{{n64}}n64_{{n32}}n32_{{n8}}n8_{{activ}}activ_{{rep}}rep.h5"

NREPS = 2
dnn_files = []
for arch in archs:
    for activ in activations:
        for nsample in nsamples:
            for rep in range(NREPS):
                kwargs = {**arch, 'rep': rep, 'activ': activ, 'nsamples': nsample}
                dnn_files.append(MODEL_FILE.format(**kwargs))
                dnn_files.append(KERAS_FILE.format(**kwargs))

rule msprime:
  input: f"msprime_bgs_{name}.json" # same as config file
  output: f"../data/msprime_sims/msprime_bgs_{name}_{{nsamples}}nsamps.npz"
  params: ncores=30
  shell:
    """
    python ../tools/msprime_bgs.py --nsamples {wildcards.nsamples} --ncores {params.ncores} --outfile {output} --model {model} {input}
    """

rule process_data:
  input: json=f"msprime_bgs_{name}.json", npz=f"../data/msprime_sims/msprime_bgs_{name}_{{nsamples}}nsamps.npz"
  output: f"../data/msprime_sims/msprime_bgs_{name}_{{nsamples}}nsamps.pkl"
  shell:
     """
     python ../tools/fit_sims.py data --outfile {output} {input.json} {input.npz}
     """

rule fit_dnn:
  input: f"../data/msprime_sims/msprime_bgs_{name}_{{nsamples}}nsamps.pkl"
  output: model=MODEL_FILE, h5=KERAS_FILE
  shell:
     """
     python ../tools/fit_sims.py fit --outfile {output.model} --batch-size 128 --n128 {wildcards.n128} --n64 {wildcards.n64} --n32 {wildcards.n32} --n8 {wildcards.n8} --activation {activ} {input} 
     """

rule sims:
  input: sim_file 

rule data:
  input: data_file

rule train:
  input: dnn_files 

