import os


fullbgs_dir = "fullbgs_dist"
#fullbgs_avail = [os.path.join(fullbgs_dir, f) for f in os.listdir(fullbgs_dir) if f.endswith("recap.tree")]

rule fullbgs_data:
  input: fullbgs_dir
  output: f"{fullbgs_dir}_data.npz"
  shell:
      """
      python ../../tools/trees2data.py --suffix "treeseq.tree" --ncores 10 --outfile {output} {input}
      """

rule all:
  input: f"{fullbgs_dir}_data.npz"
