import numpy as np
np.random.seed(0)

SEED_MAX = 2**32 - 1 

from bgspy.likelihood import BGSEstimator

NRUNS = 20_000

res = [f"runs/hg38_test_results_{seed}.npz" for seed in np.random.randint(0, SEED_MAX, NRUNS)]

rule optim_run:
  input: "hg38_test_data.npz"
  output: "runs/hg38_test_results_{seed}.npz"
  run: 
    seed = int(wildcards.seed)
    mle = BGSEstimator.from_npz(input[0])
    Y = np.load(input[0])['Y']
    mle.fit(Y, nruns=100, ncores=10, seed=seed)
    mle.save_runs(output[0])

rule merge:
  input: res
  output: "run_results.npz"
  run: 
    nlls = []
    starts = []
    thetas = []
    success = []
    for file in input:
      d = np.load(file)
      nlls.extend(d['nlls'])
      starts.extend(d['starts'])
      thetas.extend(d['thetas'])
      success.extend(d['success'])
    np.savez(output[0], nlls = np.array(nlls), starts=np.array(starts),
             thetas = np.array(thetas), success = np.array(success))


rule all:
  input: "run_results.npz"

    
