import numpy as np
np.random.seed(0)

from bgspy.likelihood import BGSEstimator

NRUNS = 10_000
NRUNS = 1

res = [f"runs/hg38_test_results_{seed}.npz" for seed in np.random.randint(0, SEED_MAX, NRUNS)]

rule optim_run:
  input: "hg38_test_data.npz"
  output: "runs/hg38_test_results_{seed}.npz"
  run: 
    seed = wildcards.seed
    mle = BGSEstimator.from_npz(input[0])
    Y = np.loadz(input[0]['Y'])
    mle.fit(Y, nruns=10_000)
    mle.save_runs(output[0])

rule merge:
  input: res
  output: "run_results.npz"
  run: 
    nlls = []
    starts = []
    thetas = []
    success = []
    for file in output:
      d = np.loadz(file)
      nlls.extend(d['nlls'])
      starts.extend(d['starts'])
      thetas.extend(d['thetas'])
      success.extend(d['success'])
    np.savez(filename, nlls = np.array(nlls), starts=np.arary(starts),
             thetas = np.array(thetas), success = np.array(thetas))


rule all:
  input: "run_results.npz"

    
