# main annotation files

# other params
NCORES = 20
NCORES_BOOT = 20
NSTARTS = 1000
NSTARTS_BOOT = 100

# from config
name = config["name"]
seqlens_file = config["seqlens_file"]
recmap_file = config["recmap_file"]
access_file = config["access_file"]
neut_file = config["neut_file"]
fasta_file = config["fasta_file"]
counts_dir = config["counts_dir"]
Bs_file = config["Bs_file"]
windows = [int(w) for w in config["windows"]]
blocksize = int(config["blocksize"])


rule fit:
  input: seqlens=seqlens_file, recmap_file=recmap_file,
         access_file=access_file, fasta_file=fasta_file,
         neut_file=neut_file, counts_dir=counts_dir,
         bs_file=Bs_file
  output: f'{name}/window_{{window}}/mle.pkl'
  params: ncores=NCORES, nstarts=NSTARTS
  shell:
    """
    bgspy loglik --seqlens {input.seqlens} --recmap {input.recmap_file} \
      --counts-dir {input.counts_dir} --neutral {input.neut_file} \
      --access {input.access_file} --bs-file {input.bs_file} \
      --fasta {input.fasta_file} \
      --ncores {params.ncores} --nstarts {params.nstarts} \
      --window {wildcards.window} \
      --outfile {output[0]}
    """

rule bootstrap:
  input: fit=f'{name}/window_{{window}}/mle.pkl', 
         seqlens=seqlens_file, recmap_file=recmap_file,
         access_file=access_file, fasta_file=fasta_file,
         neut_file=neut_file, counts_dir=counts_dir,
         bs_file=Bs_file
  output: f'{name}/window_{{window}}/bootstraps/bootstrap_{{boot}}.npz'
  params: ncores=NCORES_BOOT, nstarts=NSTARTS_BOOT, blocksize=blocksize
  shell:
    """
    bgspy bootstrap --fit {input.fit} \
      --B 10 --blocksize {params.blocksize} \
      --seqlens {input.seqlens} --recmap {input.recmap_file} \
      --counts-dir {input.counts_dir} --neutral {input.neut_file} \
      --access {input.access_file} --bs-file {input.bs_file} \
      --fasta {input.fasta_file} \
      --ncores {params.ncores} --nstarts {params.nstarts} \
      --window {wildcards.window} \
      --outfile {output[0]}
    """

all_results = []
for window in windows:
  all_results.append(f'{name}/window_{window}/mle.pkl')
  boots = [f"{name}/window_{window}/bootstraps/bootstrap_{b}.npz" for b in range(100)]
  all_results.extend(boots)

rule all:
  input: all_results
