import sys
sys.path.extend(['../../']) # for bprime modules

import json
from math import floor, log10
import itertools 
import numpy as np
import pyslim
import tskit
import msprime
from datetime import time
from collections import defaultdict, namedtuple
from bprime.slim import SlimRuns, read_params, time_grower
from bprime.samplers import Sampler

if not len(config):
    raise ValueError("config file not specified on command line, use --configfile config.json")

# ------- Shared Parameters -------
DATADIR = "../../data/slim_sims/"
SLIM = '~/src/SLiM_build/slim'
 
# ------- BGS segments -------
run = SlimRuns(config, dir=DATADIR, sampler=Sampler, split_dirs=3, seed=12)
run.generate()

# to get param order for SLiM file
#print(run.has_reps)
#print(next(run.slim_commands()))
#print(run.slim_call())
#print(run.filename_pattern)
#print(run.param_order)

# build the files to output 
sim_results = run.targets(["treeseq.tree"])
print(sim_results[:10])

rule all:
  input:
    sim_results

rule bgs:
  input: run.script
  output: run.wildcard_output(suffix="treeseq.tree")
  shell:
    run.slim_call(slim_cmd=SLIM)

