from Bio.AlignIO import MafIO

rule merge_mafs:
  # this trusts the right files here here, so we don't have to specify them all (WARNING)
  output: "10_primates.epo.{chrom}.maf"
  shell:
     """
     find . -name '10_primates.epo.{wildcards.chrom}_*.maf.gz' | sort | xargs -n 100 zcat > {output[0]}
     """

rule index_maf:
  input: maf="10_primates.epo.{chrom}.maf"
  output: mafidx="10_primates.epo.{chrom}.mafindex"
  run:
     db = MafIO.MafIndex(output.mafidx, input.maf, f"homo_sapiens.{wildcards.chrom}")

all_maf_idxs = [f"10_primates.epo.{chrom}.mafindex" for chrom in range(1, 23)]

rule all:
  input: all_maf_idxs
